name: afila_intern_presence
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  audioplayers: ^6.5.0
  camera: ^0.11.2
  cloud_firestore: ^6.0.1
  d_method: ^0.2.6
  dartz: ^0.10.1
  equatable: ^2.0.7
  firebase_auth: ^6.0.2
  firebase_core: ^4.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_expandable_fab: ^2.5.2
  geolocator: ^13.0.4
  google_mlkit_face_detection: ^0.13.1
  image: ^4.5.4
  image_picker: ^1.2.0
  intl: ^0.20.2
  location: ^8.0.1
  one_clock: ^2.0.2
  permission_handler: ^12.0.1
  root_checker_plus: ^1.0.0
  shared_preferences: ^2.5.3
  tflite_flutter: ^0.11.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
